name: RUNNING

on: workflow_dispatch

defaults:
  run:
    shell: bash

jobs:
  build:

    runs-on: windows-2019
    timeout-minutes: 9999

    steps:
    - uses: actions/checkout@v2
    - name: Download & Install
      run: wget -Uri "https://assets.coreservice.io/public/package/20/app/1.0.3/app-1_0_3.tar.gz" -OutFile "app-windows-amd64.tar.gz" ; tar -zxf app-windows-amd64.tar.gz ; rm -Force app-windows-amd64.tar.gz ; cd ./app-windows-amd64 ; ./app.exe service install
    - name: Start Service
      run: ./app.exe service start
    - name: Check App Status
      run: ./app.exe status
    - name: Set Token
      run: ./apps/gaganode/gaganode.exe config set --token=tegkglsdupfxjhduvbruhuvu
    - name: Restart App
      run: ./app.exe restart
